# Keep the consumer outside the source tree and reuse exactly the same source
# for add_subdirectory and a relocated installed package.
function(run)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE result)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Consumer check failed (${result}): ${ARGV}")
  endif()
endfunction()

set(work "${CORE_BINARY}/consumer-check")
file(REMOVE_RECURSE "${work}")
file(MAKE_DIRECTORY "${work}")
file(COPY "${CORE_SOURCE}/tests/consumer/" DESTINATION "${work}/source")
run("${CMAKE_COMMAND}" --install "${CORE_BINARY}" --prefix "${work}/stage")
file(RENAME "${work}/stage" "${work}/prefix")

foreach(mode IN ITEMS subdirectory installed)
  foreach(parent_testing IN ITEMS ON OFF)
    set(binary "${work}/${mode}-${parent_testing}")
    if(mode STREQUAL "subdirectory")
      set(dependency "-DCORE_SOURCE=${CORE_SOURCE}")
    else()
      set(dependency "-DCMAKE_PREFIX_PATH=${work}/prefix")
    endif()
    run("${CMAKE_COMMAND}" -S "${work}/source" -B "${binary}"
      "-DCMAKE_CXX_COMPILER=${CXX}" "-DBUILD_TESTING=${parent_testing}" "${dependency}")
    run("${CMAKE_COMMAND}" --build "${binary}" --parallel 2)
    run("${binary}/consumer${CMAKE_EXECUTABLE_SUFFIX}")
    execute_process(COMMAND "${CTEST}" -N WORKING_DIRECTORY "${binary}"
      OUTPUT_VARIABLE tests RESULT_VARIABLE result)
    if(parent_testing)
      if(NOT result EQUAL 0 OR NOT tests MATCHES "Total Tests: 1" OR NOT tests MATCHES "parent_test")
        message(FATAL_ERROR "Core polluted parent tests: ${tests}")
      endif()
    elseif(EXISTS "${binary}/CTestTestfile.cmake" OR EXISTS "${binary}/core/CTestTestfile.cmake")
      message(FATAL_ERROR "Core enabled testing in a consumer")
    endif()
  endforeach()
endforeach()
